# Thực hành

In [ ]:
#Bài 1.2
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Tính tích vô hướng bằng np.inner
tich_inner = np.inner(a, b)
print("Tích vô hướng dùng np.inner(a, b):", tich_inner)
# Tính tích vô hướng bằng np.dot
tich_dot = np.dot(a, b)
print("Tích vô hướng dùng np.dot(a, b):", tich_dot)
# Kiểm tra xem hai kết quả có giống nhau không
if tich_inner == tich_dot:
    print("Kết luận: np.inner(a, b) và np.dot(a, b) cho kết quả giống nhau khi a và b là vector 1 chiều.")
else:
    print("Kết luận: Hai kết quả KHÔNG giống nhau.")


Tích vô hướng dùng np.inner(a, b): 32
Tích vô hướng dùng np.dot(a, b): 32
Kết luận: np.inner(a, b) và np.dot(a, b) cho kết quả giống nhau khi a và b là vector 1 chiều.


In [ ]:
#Bài1.2.2
import numpy as np
a = np.array([1, 2, -3])
# Tính chuẩn 2 (L2 norm – mặc định)
norm_l2 = np.linalg.norm(a)
print(">>> np.linalg.norm(a)")
print(norm_l2)
# Tính chuẩn 2 (ghi rõ kiểu = 2)
norm_l2_explicit = np.linalg.norm(a, 2)
print(">>> np.linalg.norm(a, 2)")
print(norm_l2_explicit)
# Tính chuẩn 1 (L1 norm – tổng trị tuyệt đối)
norm_l1 = np.linalg.norm(a, 1)
print(">>> np.linalg.norm(a, 1)")
print(norm_l1)


>>> np.linalg.norm(a)
3.7416573867739413
>>> np.linalg.norm(a, 2)
3.7416573867739413
>>> np.linalg.norm(a, 1)
6.0


In [ ]:
#Bài 1.2.3
import math
import numpy as np
from scipy import linalg

# Định nghĩa hàm tính chuẩn p theo công thức
def chuan(a, p):
    return sum(abs(x) ** p for x in a) ** (1 / p)

a = np.array([1, 2, -3])
# Tính và in các chuẩn
print(">>> chuan(a, 1)")
print(chuan(a, 1))

print(">>> np.linalg.norm(a, 1)")
print(np.linalg.norm(a, 1))

print(">>> chuan(a, 2)")
print(chuan(a, 2))

print(">>> np.linalg.norm(a, 2)")
print(np.linalg.norm(a, 2))

print(">>> chuan(a, 3)")
print(chuan(a, 3))

print(">>> np.linalg.norm(a, 3)")
print(np.linalg.norm(a, 3))

print(">>> chuan(a, 1000)")
print(chuan(a, 1000))

print(">>> np.linalg.norm(a, 1000)")
try:
    print(np.linalg.norm(a, 1000))
except Exception as e:
    print("Lỗi xảy ra:", e)

# Thử với scipy.linalg
print(">>> linalg.norm(a)")
print(linalg.norm(a))

print(">>> linalg.norm(a, 100)")
print(linalg.norm(a, 100))

print(">>> linalg.norm(a, 1000)")
print(linalg.norm(a, 1000))


>>> chuan(a, 1)
6.0
>>> np.linalg.norm(a, 1)
6.0
>>> chuan(a, 2)
3.7416573867739413
>>> np.linalg.norm(a, 2)
3.7416573867739413
>>> chuan(a, 3)
3.3019272488946263
>>> np.linalg.norm(a, 3)
3.3019272488946263
>>> chuan(a, 1000)
1.0442214818467515
>>> np.linalg.norm(a, 1000)
inf
>>> linalg.norm(a)
3.7416573867739413
>>> linalg.norm(a, 100)
3.0
>>> linalg.norm(a, 1000)
inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [ ]:
#Bài 2
import numpy as np

m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])

M = np.array([v1, v2, v3, v4])
MT = M.transpose()
print(">>> MT")
print(MT)

v = (1.0 / m) * MT.dot(mi)
print(">>> v = (1.0/m)*MT.dot(mi)")
print(">>> print(v)")
print(v)


>>> MT
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
>>> v = (1.0/m)*MT.dot(mi)
>>> print(v)
[1.3 0.9 0. ]


In [ ]:
#Bài 3.1
import numpy as np
p = 0.136
q = 0.998
A = np.array([
    [q,     p],
    [1 - q, 1 - p]
])
# Bước 2: Khai báo vector v0 (trạng thái ban đầu)
v0 = np.array([0.95, 0.05])  # x0: có việc làm, y0: thất nghiệp
# Bước 3: Tính A^100 (dùng lệnh matrix_power)
A100 = np.linalg.matrix_power(A, 100)
# Bước 4: Tính vector trạng thái sau 100 tuần
v100 = A100.dot(v0)
# In kết quả
print("Ma trận A^100:")
print(A100)

print("\nTrạng thái sau 100 tuần (v100):")
print(v100)  # [x100, y100]


Ma trận A^100:
[[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]

Trạng thái sau 100 tuần (v100):
[0.98550723 0.01449277]


In [ ]:
#Bài 3.1.2
import numpy as np
# Khai báo hệ số ma trận và vế phải
A = np.array([
    [1, -68],
    [1,  1]
])
b = np.array([0, 1])

nghiem = np.linalg.solve(A, b)
print("Nghiệm của hệ (x, y):", nghiem)


Nghiệm của hệ (x, y): [0.98550725 0.01449275]


In [ ]:
#Bài 3.1.3
import sympy as sym
x, y = sym.symbols('x y')
# Vector ẩn và hệ số
xy = sym.Matrix([x, y])
A = sym.Matrix([[1, -68], [1, 1]])
v = sym.Matrix([0, 1])
# Giải hệ phương trình
nghiem = sym.solve([A * xy - v])
print(sym.pretty(nghiem))


⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [ ]:
#Bài 3.2
import numpy as np
A = np.array([
    [1, 6],
    [5, 2]
])
# Khai báo vector riêng u
u = np.array([6, -5])
# Tính tích Au
Au = A.dot(u)
# Tính -4u
lambda_u = -4 * u

print("A * u =", Au)
print("-4 * u =", lambda_u)
if np.allclose(Au, lambda_u):
    print("✅ Đúng: A * u = -4 * u, u là vector riêng với trị riêng λ = -4")
else:
    print("❌ Sai: Không thỏa mãn A * u = -4 * u")


A * u = [-24  20]
-4 * u = [-24  20]
✅ Đúng: A * u = -4 * u, u là vector riêng với trị riêng λ = -4


In [ ]:
#Bài 3.2.2
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)

A = sympy.Matrix([
    [2, 3],
    [3, -6]
])
# Thiết lập phương trình đặc trưng: det(Lambda*I - A) = 0
phuongtrinh = sympy.Eq(sympy.det(Lambda * I - A), 0)
# Giải phương trình tìm trị riêng
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu, 4) for phantu in nghiem])
print(sympy.pretty(nghiem))


[-7.000, 3.000]
[-7, 3]


In [ ]:
#Bìa 3.3
import numpy as np
from numpy import linalg as LA
A = np.array([[2, 3],
              [3, -6]])

D = np.array([[-7, 0],
              [0, 3]])

P = np.array([[-1.0/3, 3],
              [1, 1]])
# Tính nghịch đảo của P
P1 = LA.inv(P)
# Tính D^2 (lũy thừa ma trận chéo dễ)
print(">>> D ** 2:")
print(D ** 2)
# In P^(-1)
print(">>> P^(-1):")
print(P1)
# Tính P @ D^1000 @ P^(-1)
D_1000 = D ** 1000
result = P @ D_1000 @ P1
print(">>> P @ D^1000 @ P^(-1):")
print(result)
# Kiểm tra A * P và P * D
print(">>> A.dot(P):")
print(A.dot(P))
print(">>> P.dot(D):")
print(P.dot(D))


>>> D ** 2:
[[49  0]
 [ 0  9]]
>>> P^(-1):
[[-0.3  0.9]
 [ 0.3  0.1]]
>>> P @ D^1000 @ P^(-1):
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
>>> A.dot(P):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
>>> P.dot(D):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]


# Bài tập


In [ ]:
#Bài 1
import numpy as np
import math

a = np.array([1, 2, 3])
# a. Dùng a.dot(a)
mag_a = np.sqrt(a.dot(a))
print("a. np.sqrt(a.dot(a)) =", mag_a)
# b. Dùng toán tử @
mag_b = np.sqrt(a @ a)
print("b. np.sqrt(a @ a) =", mag_b)
# c. Dùng np.inner
mag_c = np.sqrt(np.inner(a, a))
print("c. np.sqrt(np.inner(a, a)) =", mag_c)
# d. Dùng lambda và vòng lặp
mag_d_func = lambda x: math.sqrt(sum(i**2 for i in x))
mag_d = mag_d_func(a)
print("d. lambda sqrt(sum(i**2)) =", mag_d)


a. np.sqrt(a.dot(a)) = 3.7416573867739413
b. np.sqrt(a @ a) = 3.7416573867739413
c. np.sqrt(np.inner(a, a)) = 3.7416573867739413
d. lambda sqrt(sum(i**2)) = 3.7416573867739413


In [ ]:
#Bài 2
import numpy as np
from numpy import linalg as LA
from math import acos, degrees

u = np.array([2, 3])
v = np.array([4, -1])
# --- a. Khoảng cách giữa 2 vector ---
khoang_cach = LA.norm(u - v)
print("a. Khoảng cách ||u - v|| =", khoang_cach)
# --- b. Góc giữa 2 vector ---
dot_product = np.dot(u, v)
norm_u = LA.norm(u)
norm_v = LA.norm(v)
# Tính cos(theta) và theta (radian và độ)
cos_theta = dot_product / (norm_u * norm_v)
theta_rad = acos(cos_theta)
theta_deg = degrees(theta_rad)
print("b. Góc giữa u và v (radian):", theta_rad)
print("   Góc giữa u và v (độ):", theta_deg)
# --- c. Phép chiếu trực giao ---
proj_coef = dot_product / np.dot(v, v)
p = proj_coef * v
print("c. Phép chiếu trực giao p =", p)


a. Khoảng cách ||u - v|| = 4.47213595499958
b. Góc giữa u và v (radian): 1.2277723863741932
   Góc giữa u và v (độ): 70.3461759419467
c. Phép chiếu trực giao p = [ 1.17647059 -0.29411765]
