In [3]:
#Bài 1
import numpy as np
from numpy.linalg import norm
from math import degrees, acos
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])

# a) Tổng A + B và tích số 3A - 2B
sum_AB = A + B
lin_comb = 3 * A - 2 * B

# b) Tích vô hướng và góc giữa 2 vector
dot_AB = np.dot(A, B)
cos_theta = dot_AB / (norm(A) * norm(B))
theta_deg = degrees(acos(cos_theta))

# c) Tích ma trận C^T * C
CTC = C.T @ C

# In kết quả
print("a) A + B =", sum_AB)
print("   3A - 2B =", lin_comb)

print("\nb) A · B =", dot_AB)
print("   Góc giữa A và B (độ):", round(theta_deg, 3))

print("\nc) C^T * C =\n", CTC)


a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]

b) A · B = -8
   Góc giữa A và B (độ): 108.376

c) C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [4]:
#Bài 2
import numpy as np
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# a) Tích M x N
product = M @ N

# b) Định thức của ma trận M (nếu có thể)
try:
    det_M = np.linalg.det(M)
    det_msg = f"Định thức của M: {round(det_M, 2)}"
except np.linalg.LinAlgError:
    det_msg = "Không thể tính định thức vì M không phải là ma trận vuông."

# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)

# In kết quả
print("a) Tích M x N:\n", product)
print("\nb)", det_msg)
print("\nc) Hạng của ma trận N:", rank_N)


a) Tích M x N:
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của M: 0.0

c) Hạng của ma trận N: 2


In [5]:
#Bài 3
import numpy as np
P = np.array([
    [2, 1, 0, -1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])
b = np.array([4, 7, 9, 5])
# a) Tính ma trận nghịch đảo của P (nếu có)
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo P⁻¹:\n", np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (det(P) = 0)")
# b) Giải hệ phương trình x = P⁻¹ * b
try:
    x = np.linalg.solve(P, b)
    print("\nb) Nghiệm của hệ phương trình:\n", np.round(x, 3))
except np.linalg.LinAlgError:
    print("\nb) Không thể giải hệ phương trình vì P không khả nghịch")
# c) Kiểm tra lại bằng cách nhân P * x = b?
if 'x' in locals():
    check = np.dot(P, x)
    print("\nc) Kiểm tra lại P * x:\n", np.round(check, 3))
    print("   So sánh với b:", b)


a) Ma trận nghịch đảo P⁻¹:
 [[ 0.477 -0.182  0.045  0.068]
 [ 0.034  0.273 -0.068  0.148]
 [-0.114  0.091  0.227 -0.159]
 [-0.011 -0.091  0.023  0.284]]

b) Nghiệm của hệ phương trình:
 [1.386 2.17  1.432 0.943]

c) Kiểm tra lại P * x:
 [4. 7. 9. 5.]
   So sánh với b: [4 7 9 5]


In [18]:
#Bài 4
import numpy as np

# a) Tìm giá trị riêng và vector riêng
Q = np.array([
    [4, -1, 0],
    [1, 3, -2],
    [0, 1, 2]
])
eigenvalues, eigenvectors = np.linalg.eig(Q)
# a) Giá trị riêng
print("a) Các giá trị riêng của Q:")
print(np.round(eigenvalues, 3))
# b) Vector riêng tương ứng
print("\nb) Các vector riêng (cột là vector riêng tương ứng):")
print(np.round(eigenvectors, 3))
# c) Chuẩn hóa vector riêng
norm_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("\nc) Vector riêng sau chuẩn hóa (độ dài = 1):")
print(np.round(norm_vectors, 3))


a) Các giá trị riêng của Q:
[3.453+0.j    2.773+1.468j 2.773-1.468j]

b) Các vector riêng (cột là vector riêng tương ứng):
[[ 0.833+0.j    -0.262-0.314j -0.262+0.314j]
 [ 0.455+0.j    -0.782+0.j    -0.782-0.j   ]
 [ 0.313+0.j    -0.22 +0.417j -0.22 -0.417j]]

c) Vector riêng sau chuẩn hóa (độ dài = 1):
[[ 0.833+0.j    -0.262-0.314j -0.262+0.314j]
 [ 0.455+0.j    -0.782+0.j    -0.782+0.j   ]
 [ 0.313+0.j    -0.22 +0.417j -0.22 -0.417j]]


In [9]:
import numpy as np
R = np.array([
    [1, -2, 3],
    [2,  0, 1],
    [-1, 1, 4]
])
b = np.array([10, 8, 7])
# a) Giải hệ phương trình Rx = b
x_solve = np.linalg.solve(R, b)
print("a) Nghiệm x của hệ phương trình Rx = b:")
print("   x =", np.round(x_solve, 3))
# b) Kiểm tra khả nghịch và giải lại bằng nghịch đảo nếu có
det_R = np.linalg.det(R)
if det_R != 0:
    R_inv = np.linalg.inv(R)
    x_via_inverse = R_inv @ b
    print("\nb) R khả nghịch vì det(R) =", round(det_R, 3))
    print("   Nghiệm x tính bằng R⁻¹ @ b:", np.round(x_via_inverse, 3))
    print("   So sánh với np.linalg.solve:", np.allclose(x_solve, x_via_inverse))
else:
    print("\nb) R không khả nghịch vì det(R) =", round(det_R, 3))
# c) Tính chuẩn Frobenius của ma trận R
frobenius_norm = np.linalg.norm(R, ord='fro')
print("\nc) Chuẩn Frobenius của R =", round(frobenius_norm, 3))


a) Nghiệm x của hệ phương trình Rx = b:
   x = [2.783 0.043 2.435]

b) R khả nghịch vì det(R) = 23.0
   Nghiệm x tính bằng R⁻¹ @ b: [2.783 0.043 2.435]
   So sánh với np.linalg.solve: True

c) Chuẩn Frobenius của R = 6.083
