#Bài thực hành

In [ ]:
#Bài 1
import numpy as np

D = np.array([[1, 2], [3, 4]])
try:
    np.copyto(E, D)
except NameError as e:
    print("Lỗi:", e)

E = np.array([[1, 2], [3, 5]])

np.copyto(E, D)

print("Ma trận E sau khi copy từ D:")
print(E)


Lỗi: name 'E' is not defined
Ma trận E sau khi copy từ D:
[[1 2]
 [3 4]]


In [ ]:
# Bài 1.2
import numpy as np

print("=== Ví dụ 1: Sử dụng numpy.matrix chứa phần tử là object ===")
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
C = np.matrix([[x, y], [1, 2]], dtype=object)
print("Ma trận C:")
print(C)

print("\n=== Ví dụ 2: Không thể tạo np.matrix 3 chiều ===")
try:
    A = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
except ValueError as e:
    print("Lỗi:", e)

print("\n=== Ví dụ 3: Tạo np.array 3 chiều thành công ===")
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Mảng A:")
print(A)


=== Ví dụ 1: Sử dụng numpy.matrix chứa phần tử là object ===
Ma trận C:
[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]

=== Ví dụ 2: Không thể tạo np.matrix 3 chiều ===
Lỗi: matrix must be 2-dimensional

=== Ví dụ 3: Tạo np.array 3 chiều thành công ===
Mảng A:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Bài 1.3
from numpy import matlib
G = matlib.identity(5)
print("Ma trận G (identity 5x5):")
print(G)

H = matlib.randn(3, 2)
print("\nMa trận H (randn 3x2):")
print(H)

K = matlib.zeros([4, 4])
print("\nMa trận K (zeros 4x4):")
print(K)


Ma trận G (identity 5x5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Ma trận H (randn 3x2):
[[ 0.42263815  1.36152438]
 [-0.53197675 -0.24578689]
 [-1.88549987  0.9554199 ]]

Ma trận K (zeros 4x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Bâi 2.2
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
for i in range(len(c)):
    ci = np.array([[c[i], 1], [1, 0]], dtype=object)
    if i == 0:
        M = ci
    else:
        M = M @ ci

print("Ma trận M:")
print(M)

pi_approx = M[0, 0] / M[1, 0]
print("\nSố Pi xấp xỉ:")
print(pi_approx)



Ma trận M:
[[165707065 80143857]
 [52746197 25510582]]

Số Pi xấp xỉ:
3.1415926535897936


In [ ]:
#Bài 3
import numpy as np

X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5]
])

Y = np.array([
    [1],
    [2],
    [4],
    [4],
    [6]
])


XT = X.T

A1 = np.linalg.inv(XT.dot(X))

# Tính A2 = XT Y
A2 = XT.dot(Y)
# Tính A = A1 A2
A = A1.dot(A2)
# Hiển thị hệ số a0, a1
a0, a1 = A.flatten()
print(f"Phương trình gần đúng nhất: y = {a0:.1f} + {a1:.1f}x")
# Tính sai số
y_du_doan = X.dot(A)
sai_so = np.sum((y_du_doan - Y) ** 2)
print(f"Sai số là: {sai_so:.1f}")


Phương trình gần đúng nhất: y = -0.2 + 1.2x
Sai số là: 0.8


# Bài Tập


In [ ]:
#Bài tạp 1
import numpy as np

# Dữ liệu: (x, y) = {(0, 10), (1, 8), (2, 7), (3, 5), (4, 2)}
x_data = np.array([0, 1, 2, 3, 4])
y_data = np.array([10, 8, 7, 5, 2])

X = np.column_stack((np.ones(len(x_data)), x_data))


A1 = np.linalg.inv(X.T @ X)

A2 = X.T @ y_data

A = A1 @ A2

a0, a1 = A
print(f"Phương trình tuyến tính gần đúng nhất: y = {a0:.1f} + {a1:.1f}x")

# Tính sai số (tổng bình phương sai số)
y_du_doan = X @ A
sai_so = np.sum((y_du_doan - y_data) ** 2)
print(f"Tổng bình phương sai số: {sai_so:.2f}")


Phương trình tuyến tính gần đúng nhất: y = 10.2 + -1.9x
Tổng bình phương sai số: 1.10
