In [19]:
#BÀI 1
import numpy as np
from numpy.linalg import norm
from math import acos, degrees
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])

# a) Tính tổng A + B và tích số 2A + 3B
sum_AB = A + B
linear_comb = 2 * A + 3 * B

print("a)")
print("A + B =", sum_AB)
print("2A + 3B =", linear_comb)

# b)  Tính tích vô hướng A · B và góc giữa hai vector (tính bằng độ, làm tròn đến 3 chữ số thập phân)
dot_product = np.dot(A, B)
norm_A = norm(A)
norm_B = norm(B)
cos_theta = dot_product / (norm_A * norm_B)
theta_rad = acos(cos_theta)
theta_rad_rounded = round(theta_rad, 3)

print("\nb)")
print("A · B =", dot_product)
print("Góc giữa A và B (radian) =", theta_rad_rounded)

# c) Tính tích ma trận C * C^T
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
CCT = np.dot(C, C.T)

print("\nc)")
print("C * C^T =")
print(CCT)


a)
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

b)
A · B = -5
Góc giữa A và B (radian) = 1.738

c)
C * C^T =
[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [20]:
#BÀI 2
import numpy as np
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])
# a) Tính tích M x N
product = np.dot(M, N)
print("a) M × N =")
print(product)
# b) Tính định thức ma trận M
if M.shape[0] == M.shape[1]:
    det_M = np.linalg.det(M)
    print("\nb) Định thức của M =", round(det_M, 3))
else:
    print("\nb) Ma trận M không phải vuông nên không tính được định thức.")
# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của ma trận N =", rank_N)


a) M × N =
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của M = 409.0

c) Hạng của ma trận N = 4


In [21]:
#Bài 3
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

b = np.array([6, 8, -3, 7])

# a) Tìm ma trận nghịch đảo của P. Nếu không khả nghịch, giải thích lý do
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P là:")
    print(np.round(P_inv, 3))  # Làm tròn cho dễ đọc
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (định thức bằng 0).")

# b)Giải hệ phương trình trên bằng cách sử dụng nghịch đảo ma trận
try:
    x = np.dot(P_inv, b)
    print("\nb) Nghiệm của hệ phương trình là:")
    print(np.round(x, 3))
except:
    print("\nb) Không giải được hệ vì P không khả nghịch.")
# c)Kiểm tra nghiệm bằng cách nhân ma trận P với vector nghiệm và so sánh với vector hằng số.

if 'x' in locals():
    b_check = np.dot(P, x)
    print("\nc) Kiểm tra lại: P * x =")
    print(np.round(b_check, 3))
    print("So sánh với b gốc:", b)



a) Ma trận nghịch đảo của P là:
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b) Nghiệm của hệ phương trình là:
[ 1.4    1.371 -0.557  1.586]

c) Kiểm tra lại: P * x =
[ 6.  8. -3.  7.]
So sánh với b gốc: [ 6  8 -3  7]


In [22]:
#BÀI 4
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

# a) Tìm các giá trị riêng của Q
giatririeng, vectorrieng = np.linalg.eig(Q)
print("a) Các giá trị riêng :")
print(giatririeng)

# b) Tìm các vector riêng tương ứng với các giá trị riêng
print("\nb) Các vector riêng tương ứng (cột vector):")
print(vectorrieng)

# c) Chuẩn hóa các vector riêng (độ dài bằng 1)
dinhmuc_vectors = vectorrieng / np.linalg.norm(vectorrieng, axis=0)
print("\nc) Các vector riêng sau khi chuẩn hóa (unit length):")
print(dinhmuc_vectors)


a) Các giá trị riêng :
[6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]

b) Các vector riêng tương ứng (cột vector):
[[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]

c) Các vector riêng sau khi chuẩn hóa (unit length):
[[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


In [18]:
# Bài 5
import numpy as np
R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])
b = np.array([12, 5, 9])
#a)  Giải hệ phương trình Rx = b bằng phương pháp np.linalg.solve()
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ phương trình Rx = b là:")
print(x)
#b) Xác định xem ma trận R có khả nghịch không. Nếu có, tính ma trận nghịch đảo và dùng nó để giải lại hệ. So sánh hai nghiệm.
det_R = np.linalg.det(R)
print("\nb) Định thức của R:", det_R)
if det_R != 0:
    print("=> Ma trận R khả nghịch.")
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo R⁻¹:\n", R_inv)
    # Giải lại hệ bằng R⁻¹.b
    x_check = R_inv @ b
    print("Nghiệm giải lại bằng R⁻¹.b là:")
    print(x_check)
    # So sánh hai nghiệm
    is_close = np.allclose(x, x_check)
    print("So sánh với nghiệm ở phần a):", "Trùng khớp" if is_close else "Khác nhau ")
else:
    print("=> Ma trận R không khả nghịch.")
#c) Tính chuẩn Frobenius của ma trận R
fro_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của ma trận R là:", fro_norm)


a) Nghiệm của hệ phương trình Rx = b là:
[2.78823529 1.52941176 1.18823529]

b) Định thức của R: 85.00000000000001
=> Ma trận R khả nghịch.
Ma trận nghịch đảo R⁻¹:
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
Nghiệm giải lại bằng R⁻¹.b là:
[2.78823529 1.52941176 1.18823529]
So sánh với nghiệm ở phần a): Trùng khớp

c) Chuẩn Frobenius của ma trận R là: 8.0
